# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calendar.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calendar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61lendar.proto\x12\x08\x63\x61lendar\"\x07\n\x05\x45mpty\"n\n\x0c\x45ventDetails\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\t\x12\x10\n\x08\x65\x64\x64_time\x18\x04 \x01(\t\x12\x14\n\x0cparticipants\x18\x05 \x03(\t\"8\n\x13\x43reateEventResponse\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"H\n\tEventList\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.calendar.EventDetails\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\x8b\x01\n\x0f\x43\x61lendarService\x12\x44\n\x0b\x43reateEvent\x12\x16.calendar.EventDetails\x1a\x1d.calendar.CreateEventResponse\x12\x32\n\nListEvents\x12\x0f.calendar.Empty\x1a\x13.calendar.EventListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_EVENTDETAILS']._serialized_start=37
  _globals['_EVENTDETAILS']._serialized_end=147
  _globals['_CREATEEVENTRESPONSE']._serialized_start=149
  _globals['_CREATEEVENTRESPONSE']._serialized_end=205
  _globals['_EVENTLIST']._serialized_start=207
  _globals['_EVENTLIST']._serialized_end=279
  _globals['_CALENDARSERVICE']._serialized_start=282
  _globals['_CALENDARSERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
